### ISSUE TITLE
OAuth가 뭘까

### ISSUE THREAD

**Issue by ggsno** [Learning-React-42study/Learning-React#11]
223page
깃허브나 페이스북 같은 제 3자로부터 OAuth와 같은 열린 표준을 사용해 토큰을 얻을 수 도 있다

**Comment by humonnom** [comment]
## OAuth란?
OAuth("Open Authorization")는 인터넷 사용자들이 비밀번호를 제공하지 않고 다른 웹사이트 상의 자신들의 정보에 대해 웹사이트나 애플리케이션의 접근 권한을 부여할 수 있는 공통적인 수단으로서 사용되는, 접근 위임을 위한 [개방형 표준](https://ko.wikipedia.org/wiki/%EA%B0%9C%EB%B0%A9%ED%98%95_%ED%91%9C%EC%A4%80)이다.

## OAuth 이전의 인증
1. 기존의 기본인증
   - 아이디, 비밀번호 방식 
2. 각 애플리케이션의 방식
   - [구글](https://ko.wikipedia.org/wiki/%EA%B5%AC%EA%B8%80)의 AuthSub
   - AOL의 OpenAuth
   - 야후의 BBAuth
   - 아마존의 웹서비스 API
-> API 접근 위임에 대한 공개 표준이 없음
 
 ## OAuth 커뮤니티의 탄생
- 2007년 탄생
- 2007년 OAuth 코어 1.0 초안발표
- 2010년 OAuth 1.0 공식 표준안이 RFC 5849로 발표
